### ISSUE TITLE
能否适配一下手机端

### ISSUE THREAD

**Issue by windy1021** [ssoda01/scripts-of-tampermonkey#1]
很实用的脚本，但是在手机上使用该脚本时按钮会在切换账号时有一定遮挡，因为一直在最上层，导致点击不了切换选项，能否调整一下按钮的大小样式和位置？或者适配一下手机端？辛苦

**Comment by ssoda01** [comment]
快速修改了一下，现已发布新版本。感谢提议´͈ ᵕ `͈
